spring.profiles.active: local

spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - openai.yml
      - kafka.yml
  application:
    name: investment-service

server:
  port: ${APPLICATION_PORT:8084}
  tomcat:
    max-connections: 10000
    threads:
      max: 200
      min-spare: 20

webclient:
  base-url: ${WEBCLIENT_BASE_URL}

---
spring.config.activate.on-profile: local
spring:
  config:
    import:
      - eureka.yml
      - optional:classpath:env.properties

---
spring.config.activate.on-profile: dev
spring:
  config:
    import:
      - eureka.yml
logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

---
spring.config.activate.on-profile: prod
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
eureka:
  client:
    enabled: false
